In [4]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
#Changing Work directory
os.chdir('/content/')

In [6]:
pos = pd.read_excel('pos_sample.xlsx')

In [8]:
#reading data
pos.head()

    SKU_ID  Page_traffic  Units_sold Segment
0  SKU1011        4119.0         697  Makeup
1  SKU1011        4074.0        1027  Makeup
2  SKU1011        4897.0        1037  Makeup
3  SKU1011        4783.0        1184  Makeup
4  SKU1011        3789.0         876  Makeup

In [10]:
#View the shape of data
pos.shape

(3993, 4)

## Steps we will follow to build a model for doing prediction

1. We will begin with dividing the data set into train and valid.
2. Then we will perform mean based and rule based prediction
3. And finally we will evaluate models correctness using MAE

# Step 1 dividing the data

In [12]:
# Importing the train test split to split data
from sklearn.model_selection import train_test_split

In [18]:
# Splitting data
pos_train, pos_valid = train_test_split(pos, test_size = 0.2, random_state = 9)

In [20]:
# Checking the shape
pos_train.shape, pos_valid.shape

((3194, 4), (799, 4))

# 2. Performing mean based pridiction

In [21]:
# mean of overall unit sold for train data and converting it into integers since units sold can't be integers
unit_sold_mean = int(pos_train['Units_sold'].mean())
unit_sold_mean

1157

In [22]:
pos_valid['Pred_Mean_Units_Sold'] = unit_sold_mean
pos_valid.head()

       SKU_ID  Page_traffic  Units_sold    Segment  Pred_Mean_Units_Sold
2137   SKU252        3202.0        1303   Skincare                  1157
118   SKU1056        4423.0        1586     Makeup                  1157
903    SKU145        4562.0        1522  Hair Care                  1157
1966   SKU199        4775.0        1495     Makeup                  1157
2335   SKU271        2953.0        1138     Makeup                  1157

# 3. Evaluate Prediction

In [24]:
#Importing mean absolute error
from sklearn.metrics import mean_absolute_error

In [28]:
# MAE of overall units sold
mean_absolute_error(pos_valid['Units_sold'],pos_valid['Pred_Mean_Units_Sold'])

307.0475594493116

# 2nd Approach rule based model

In [33]:
#calculate the mean of units sold for pos_train by segment
mean_units_sold_by_segment = pos_train.groupby('Segment')['Units_sold'].mean().astype(int)
mean_units_sold_by_segment

Segment
Hair Care    1166
Makeup       1152
Skincare     1161
Name: Units_sold, dtype: int64

In [34]:
# creating a new column pred_Segment_Mean_Units_Sold in the pos_valid dataframe
# and assigining mean

pos_valid['Pred_Segment_Mean_Units_Sold'] = pos_valid["Segment"].map(mean_units_sold_by_segment)
pos_valid.head()

,SKU_ID,Page_traffic,Units_sold,Segment,Pred_Mean_Units_Sold,Pred_Segment_Mean_Units_Sold
2137,SKU252,3202.0,1303,Skincare,1157,1161
118,SKU1056,4423.0,1586,Makeup,1157,1152
903,SKU145,4562.0,1522,Hair Care,1157,1166
1966,SKU199,4775.0,1495,Makeup,1157,1152
2335,SKU271,2953.0,1138,Makeup,1157,1152

# Evaluation

In [39]:
mean_absolute_error(pos_valid["Units_sold"],pos_valid["Pred_Segment_Mean_Units_Sold"])

306.4267834793492